/**
 * Make → model lists for onboarding vehicle dropdowns (global + AU-common brands).
 * "Other / not listed" is handled in UI with free-text make & model.
 */

export const OTHER_MAKE_LABEL = "Other / not listed";

/** Exterior colours common in registration / insurance forms */
export const VEHICLE_COLOURS = [
  "White",
  "Black",
  "Silver",
  "Grey / gray",
  "Red",
  "Blue",
  "Green",
  "Yellow / gold",
  "Orange",
  "Brown / beige",
  "Purple / violet",
  "Pink",
  "Bronze / champagne",
  "Two-tone / other",
] as const;

export const VEHICLE_CLASSES: { value: string; label: string }[] = [
  { value: "compact", label: "Compact" },
  { value: "sedan", label: "Sedan" },
  { value: "suv", label: "SUV" },
  { value: "large_suv", label: "Large SUV" },
  { value: "electric", label: "Electric" },
];

export const SEAT_OPTIONS = [1, 2, 3, 4, 5, 6, 7] as const;

const PAIRS: [string, string[]][] = [
  [
    "Acura",
    ["CL", "ILX", "Integra", "Legend", "MDX", "NSX", "RDX", "RL", "RLX", "RSX", "TL", "TLX", "TSX", "ZDX"],
  ],
  [
    "Alfa Romeo",
    ["4C", "Giulia", "Giulietta", "GT", "GTV", "MiTo", "Spider", "Stelvio", "Tonale"],
  ],
  ["Aston Martin", ["DB11", "DB12", "DB9", "DBS", "Rapide", "Vantage", "Vanquish", "Virage", "DBX"]],
  [
    "Audi",
    [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q4 e-tron",
      "Q5",
      "Q7",
      "Q8",
      "e-tron",
      "e-tron GT",
      "RS3",
      "RS4",
      "RS5",
      "RS6",
      "RS7",
      "RS Q3",
      "RS Q8",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S8",
      "TT",
      "TTS",
      "R8",
    ],
  ],
  [
    "BMW",
    [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "i3",
      "i4",
      "i5",
      "i7",
      "i8",
      "iX",
      "iX1",
      "iX2",
      "iX3",
      "M2",
      "M3",
      "M4",
      "M5",
      "M8",
      "X1",
      "X2",
      "X3",
      "X3 M",
      "X4",
      "X4 M",
      "X5",
      "X5 M",
      "X6",
      "X6 M",
      "X7",
      "XM",
      "Z3",
      "Z4",
    ],
  ],
  ["Bentley", ["Arnage", "Azure", "Bentayga", "Brooklands", "Continental", "Flying Spur", "Mulsanne"]],
  [
    "BYD",
    ["Atto 3", "Dolphin", "Seal", "Sealion", "Tang", "Han", "Yuan Plus", "Dolphin Mini"],
  ],
  [
    "Chevrolet",
    [
      "Aveo",
      "Blazer",
      "Camaro",
      "Captiva",
      "Colorado",
      "Corvette",
      "Cruze",
      "Equinox",
      "Impala",
      "Malibu",
      "Silverado",
      "Spark",
      "Suburban",
      "Tahoe",
      "Trailblazer",
      "Traverse",
      "Trax",
    ],
  ],
  ["Chrysler", ["300", "300C", "Aspen", "Crossfire", "Grand Voyager", "Pacifica", "PT Cruiser", "Sebring", "Voyager"]],
  ["Citroën", ["Berlingo", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5", "C5 Aircross", "Grand C4", "DS3", "DS4", "DS5"]],
  ["Cupra", ["Ateca", "Born", "Formentor", "Leon", "Terramar"]],
  ["Dacia", ["Duster", "Jogger", "Logan", "Sandero", "Spring"]],
  [
    "Dodge",
    ["Avenger", "Caliber", "Caravan", "Challenger", "Charger", "Dart", "Durango", "Grand Caravan", "Journey", "Nitro", "RAM (Dodge-era)"],
  ],
  ["Ferrari", ["296", "360", "430", "458", "488", "550", "575", "599", "612", "812", "California", "F8", "FF", "F12", "GTC4", "Portofino", "Purosangue", "Roma", "SF90"]],
  ["Fiat", ["500", "500e", "500L", "500X", "Bravo", "Doblo", "Ducato", "Panda", "Punto", "Tipo"]],
  [
    "Ford",
    [
      "Bronco",
      "Bronco Sport",
      "C-MAX",
      "EcoSport",
      "Edge",
      "Escape",
      "Escort",
      "Everest",
      "Expedition",
      "Explorer",
      "F-150",
      "F-250",
      "Fiesta",
      "Focus",
      "Fusion",
      "Galaxy",
      "GT",
      "Ka",
      "Kuga",
      "Mondeo",
      "Mustang",
      "Mustang Mach-E",
      "Puma",
      "Ranger",
      "S-MAX",
      "Taurus",
      "Territory",
      "Tourneo",
      "Transit",
    ],
  ],
  ["Genesis", ["G70", "G80", "G90", "GV60", "GV70", "GV80"]],
  ["GMC", ["Acadia", "Canyon", "Envoy", "Hummer EV", "Savana", "Sierra", "Terrain", "Yukon"]],
  [
    "Honda",
    [
      "Accord",
      "BR-V",
      "City",
      "Civic",
      "CR-V",
      "CR-Z",
      "e",
      "e:NS1",
      "Element",
      "Fit / Jazz",
      "HR-V",
      "Insight",
      "Integra",
      "Legend",
      "Odyssey",
      "Passport",
      "Pilot",
      "Prelude",
      "Prologue",
      "Ridgeline",
      "S2000",
      "ZR-V",
    ],
  ],
  [
    "Hyundai",
    [
      "Accent",
      "Bayon",
      "Elantra",
      "Genesis (Hyundai-era)",
      "Getz",
      "Grandeur",
      "i20",
      "i30",
      "i40",
      "Ioniq",
      "Ioniq 5",
      "Ioniq 6",
      "Kona",
      "Kona Electric",
      "Lantra",
      "Nexo",
      "Palisade",
      "Santa Cruz",
      "Santa Fe",
      "Sonata",
      "Staria",
      "Tucson",
      "Veloster",
      "Venue",
      "Veracruz",
    ],
  ],
  ["Ineos", ["Grenadier", "Quartermaster"]],
  ["Isuzu", ["D-MAX", "MU-X", "NPR (light)"]],
  ["Jaguar", ["E-Pace", "F-Pace", "F-Type", "I-Pace", "S-Type", "XE", "XF", "XJ", "XK"]],
  [
    "Jeep",
    [
      "Cherokee",
      "Compass",
      "Commander",
      "Gladiator",
      "Grand Cherokee",
      "Grand Wagoneer",
      "Liberty / Cherokee (old)",
      "Patriot",
      "Renegade",
      "Wrangler",
    ],
  ],
  [
    "Kia",
    [
      "Carens",
      "Carnival",
      "Cerato",
      "EV6",
      "EV9",
      "Forte",
      "K3",
      "K5",
      "Niro",
      "Optima",
      "Picanto",
      "Rio",
      "Seltos",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
      "Stonic",
      "Telluride",
      "XCeed",
    ],
  ],
  ["Lamborghini", ["Aventador", "Countach", "Gallardo", "Huracán", "Murciélago", "Revuelto", "Urus"]],
  [
    "Land Rover",
    [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
    ],
  ],
  [
    "Lexus",
    [
      "CT",
      "ES",
      "GS",
      "GX",
      "HS",
      "IS",
      "LC",
      "LFA",
      "LS",
      "LX",
      "NX",
      "RC",
      "RX",
      "RZ",
      "SC",
      "TX",
      "UX",
    ],
  ],
  ["Lotus", ["Elise", "Eletre", "Emira", "Evora", "Exige"]],
  ["Maserati", ["Ghibli", "GranCabrio", "GranTurismo", "Grecale", "Levante", "MC20", "Quattroporte"]],
  [
    "Mazda",
    [
      "2",
      "3",
      "5",
      "6",
      "121",
      "323",
      "626",
      "929",
      "BT-50",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-60",
      "CX-70",
      "CX-8",
      "CX-9",
      "CX-90",
      "MPV",
      "MX-30",
      "MX-5",
      "Premacy",
      "RX-7",
      "RX-8",
      "Tribute",
    ],
  ],
  ["McLaren", ["540C", "570S", "600LT", "650S", "720S", "750S", "765LT", "Artura", "GT", "P1"]],
  [
    "Mercedes-Benz",
    [
      "A-Class",
      "B-Class",
      "C-Class",
      "CLA",
      "CLE",
      "CLK",
      "CLS",
      "E-Class",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQS",
      "G-Class",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLK",
      "GLS",
      "ML",
      "R-Class",
      "S-Class",
      "SL",
      "SLC",
      "SLK",
      "SLR",
      "SLS",
      "Sprinter (passenger)",
      "V-Class",
      "X-Class",
    ],
  ],
  ["MG", ["3", "4 Electric", "5", "6", "HS", "MG3", "MG4", "MG5", "MG6", "ZS", "RX5", "RX8"]],
  ["Mini", ["Clubman", "Convertible", "Countryman", "Coupe", "Hardtop", "Paceman", "Roadster"]],
  [
    "Mitsubishi",
    [
      "ASX",
      "Attrage / Mirage",
      "Challenger",
      "Colt",
      "Delica",
      "Eclipse",
      "Eclipse Cross",
      "Galant",
      "Grandis",
      "i-MiEV",
      "Lancer",
      "Montero / Pajero",
      "Outlander",
      "Outlander PHEV",
      "Pajero Sport",
      "Triton",
    ],
  ],
  [
    "Nissan",
    [
      "370Z",
      "Altima",
      "Ariya",
      "Cube",
      "Frontier / Navara",
      "GT-R",
      "Juke",
      "Kicks",
      "Leaf",
      "Maxima",
      "Micra",
      "Murano",
      "Note",
      "NV200",
      "Pathfinder",
      "Patrol",
      "Pulsar",
      "Qashqai",
      "Quest",
      "Rogue",
      "Sentra",
      "Skyline",
      "Terrano",
      "Tiida",
      "Titan",
      "Versa",
      "X-Trail",
    ],
  ],
  ["Opel / Vauxhall", ["Adam", "Astra", "Corsa", "Crossland", "Grandland", "Insignia", "Meriva", "Mokka", "Vectra", "Zafira"]],
  [
    "Peugeot",
    [
      "1007",
      "2008",
      "205",
      "206",
      "207",
      "208",
      "3008",
      "301",
      "307",
      "308",
      "4008",
      "406",
      "407",
      "408",
      "5008",
      "508",
      "607",
      "807",
      "e-208",
      "e-2008",
      "Partner",
      "Rifter",
    ],
  ],
  ["Polestar", ["1", "2", "3", "4"]],
  [
    "Porsche",
    [
      "911",
      "918",
      "928",
      "944",
      "968",
      "Boxster",
      "Cayenne",
      "Cayman",
      "Macan",
      "Panamera",
      "Taycan",
    ],
  ],
  ["Ram", ["1500", "2500", "3500", "Charger (legacy)", "Dakota", "Promaster"]],
  [
    "Renault",
    [
      "Arkana",
      "Austral",
      "Captur",
      "Clio",
      "Espace",
      "Fluence",
      "Grand Scenic",
      "Kadjar",
      "Kangoo",
      "Koleos",
      "Laguna",
      "Megane",
      "Scenic",
      "Talisman",
      "Twingo",
      "Zoe",
    ],
  ],
  ["Rivian", ["R1S", "R1T"]],
  ["Rolls-Royce", ["Cullinan", "Dawn", "Ghost", "Phantom", "Spectre", "Wraith"]],
  [
    "Subaru",
    [
      "BRZ",
      "Crosstrek / XV",
      "Forester",
      "Impreza",
      "Justy",
      "Legacy",
      "Levorg",
      "Liberty",
      "Outback",
      "Solterra",
      "SVX",
      "Tribeca",
      "WRX",
    ],
  ],
  [
    "Suzuki",
    [
      "Across",
      "Alto",
      "Baleno",
      "Celerio",
      "Grand Vitara",
      "Ignis",
      "Jimny",
      "Kizashi",
      "S-Cross",
      "Splash",
      "Swift",
      "SX4",
      "Vitara",
      "XL-7",
    ],
  ],
  [
    "Tesla",
    ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck", "Roadster"],
  ],
  [
    "Toyota",
    [
      "86 / GR86",
      "Alphard",
      "Auris",
      "Avalon",
      "Avensis",
      "bZ4X",
      "C-HR",
      "Camry",
      "Celica",
      "Corolla",
      "Corolla Cross",
      "Crown",
      "Echo",
      "FJ Cruiser",
      "Fortuner",
      "GR Corolla",
      "GR Yaris",
      "HiAce",
      "Highlander / Kluger",
      "Hilux",
      "iQ",
      "Land Cruiser",
      "Land Cruiser Prado",
      "MR2",
      "Prius",
      "Prius c",
      "Prius v",
      "RAV4",
      "Sequoia",
      "Sienna",
      "Starlet",
      "Supra",
      "Tacoma",
      "Tundra",
      "Venza",
      "Yaris",
      "Yaris Cross",
    ],
  ],
  [
    "Volkswagen",
    [
      "Amarok",
      "Arteon",
      "Beetle",
      "Bora",
      "Caddy",
      "CC",
      "Corrado",
      "Eos",
      "Fox",
      "Golf",
      "Golf R",
      "Golf GTI",
      "ID.3",
      "ID.4",
      "ID.5",
      "ID. Buzz",
      "Jetta",
      "Passat",
      "Phaeton",
      "Polo",
      "Routan",
      "Scirocco",
      "Sharan",
      "T-Cross",
      "T-Roc",
      "Taigo",
      "Taos",
      "Tiguan",
      "Touareg",
      "Touran",
      "Up!",
    ],
  ],
  [
    "Volvo",
    [
      "C30",
      "C40",
      "C70",
      "EX30",
      "EX90",
      "S40",
      "S60",
      "S70",
      "S80",
      "S90",
      "V40",
      "V50",
      "V60",
      "V70",
      "V90",
      "XC40",
      "XC60",
      "XC70",
      "XC90",
    ],
  ],
  [
    "Holden",
    [
      "Astra",
      "Barina",
      "Calais",
      "Caprice",
      "Captiva",
      "Colorado",
      "Commodore",
      "Cruze",
      "Equinox",
      "Jackaroo",
      "Monaro",
      "Rodeo",
      "Statesman",
      "Trax",
      "Ute",
      "Vectra",
      "Zafira",
    ],
  ],
];

export const VEHICLE_MODELS_BY_MAKE: Record<string, string[]> = Object.fromEntries(
  PAIRS.map(([make, models]) => [make, [...models].sort((a, b) => a.localeCompare(b))])
);

export const VEHICLE_MAKES_SORTED: string[] = PAIRS.map(([m]) => m).sort((a, b) =>
  a.localeCompare(b)
);
